# Generated by Django 3.2.23 on 2023-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_child_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.PositiveIntegerField(max_length=8),
        ),
    ]
