# Generated by Django 3.2.23 on 2023-12-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_employee_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount_to_pay',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('home_babysitter', 'Home Babysitter'), ('home_tutor', 'Home Tutor'), ('school_babysitter', 'School Babysitter'), ('school_tutor', 'School Tutor'), ('home_playbuddy', 'Home Playbuddy'), ('course_program', 'Course/Program')], default='home_babysitter', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='child_name',
            field=models.CharField(default='credit_card', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_option',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('cash', 'Cash')], default='credit_card', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='parent_name',
            field=models.CharField(max_length=255),
        ),
    ]
