# Generated by Django 3.2.23 on 2023-12-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20231203_2334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSection',
            new_name='About',
        ),
    ]
